#POST http://localhost:5000/predict
#Content-Type: application/json
#
#{
#  "symptoms": "Am palpitatii si durere de cap, dar nu am tuse"
#}


#Create admin
#Complete with your data
POST http://localhost:8080/api/auth/create-admin
Content-Type: application/json

{
  "secretKey": "Ciscosecpa55",
  "email": "",
  "password": ""
}


